---
-
  hosts: "{{ host }}"
  gather_facts: false
  
  tasks:
  - name: Creating an empty file
    file:
      path: "/tmp/testing.txt"
      state: touch

  - name: Debug hostname
    msg: "IP is {{ host }}"
    
