---
-
  hosts: "{{ host }}"
  gather_facts: false
  
  tasks:
  - name: Creating an empty file
    file:
      path: "/tmp/testing.txt"
      state: touch

  - name: Print HOST IP
    debug:
      msg: "IP IS: {{ host }}"
