---
- name: Create files
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Creating an empty file
    file:
      path: "/tmp/{{ filename }}"
      state: touch
#    register: result
#    ignore_unreachable: true
#  - fail:
#    when: result.unreachable
      

  - name: Get hostname
    shell: echo $HOSTNAME
    register: result

  - name: Print hostname
    debug:
      msg: "Hostname is: {{ result }}"
